### PR TITLE
Port tests to openssl 1.1

### PR DESCRIPTION
**Pull request by kanavin**
This fixes API compaitbility errors that happen when building with openssl 1.1.0 and later.

### CODE REVIEW

**Comment by cristian-stoica** [comment]
@kanavin This fix will probably break the build with previous versions of OpenSSL. Does it fix https://github.com/cryptodev-linux/cryptodev-linux/issues/22 ? It would be preferable an #ifdef patch that works with all current maintained OpenSSL versions.

**Comment by cristian-stoica** [comment]
OpenSSL version reference: https://www.openssl.org/docs/manmaster/man3/OPENSSL_VERSION_NUMBER.html

**Comment by kanavin** [comment]
Now fixed.

**Comment by cristian-stoica** [comment]
@kanavin Thanks for your patch

**Pull request merged**
