### PR TITLE
Release version 1.11

### PR DESCRIPTION
**Pull request by sbranden**
Signed-off-by: Scott Branden <scott.branden@broadcom.com>

### CODE REVIEW

**Comment by sbranden** [comment]
@cristian-stoica could we get a new release tag?

**Comment by cristian-stoica** [comment]
Sure let's bump the version number.

Does anyone else has patches in the works that should be included?

**Comment by sbranden** [comment]
There is another patch to cryptodev applied in openembedded builds:
https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/recipes-kernel/cryptodev/files/0001-Disable-installing-header-file-provided-by-another-p.patch?h=master

But I don't know if this should be applied to your version?

**Comment by cristian-stoica** [comment]
That patch is specific to a third party installation where cryptodev.h is indeed installed by another package similar to cryptodev (I don't remember details; ocf-linux maybe?). It should not be part of cryptodev-linux.

We'll wait a couple of weeks and if there are no other patches to merge then we'll bump the version.

**Comment by cristian-stoica** [comment]
Pull request merged. Thank you.

**Pull request closed without merging**
